# Generated by Django 2.0.7 on 2018-08-27 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=10, unique=True, verbose_name='Логін')),
                ('surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер мобільного')),
            ],
            options={
                'verbose_name_plural': 'Клієнти',
                'verbose_name': 'клієнт',
            },
        ),
        migrations.CreateModel(
            name='ClientResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Відгук')),
                ('response_type', models.BooleanField(choices=[(True, 'Позитивний'), (False, 'Негативний')], default=False, verbose_name='Тип')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата і час')),
            ],
            options={
                'verbose_name_plural': 'Відгуки',
                'verbose_name': 'відгук',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=10, unique=True, verbose_name='Логін')),
                ('surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер мобільного')),
                ('vehicle_registration_plate', models.CharField(max_length=20, verbose_name='Номер авто')),
                ('money_balance', models.FloatField(default=0, verbose_name='Баланс на рахунку')),
                ('registration_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('likes', models.PositiveSmallIntegerField(default=0, verbose_name='Лайки')),
                ('dislikes', models.PositiveSmallIntegerField(default=0, verbose_name='Дизлайки')),
                ('fails', models.PositiveSmallIntegerField(default=0, verbose_name='Штрафи')),
                ('last_fail_date', models.DateField(blank=True, null=True, verbose_name='Дата останнього штрафу')),
                ('driver_status', models.PositiveSmallIntegerField(choices=[(0, 'Недоступний'), (1, 'Вільний'), (2, 'Зайнятий'), (3, 'Тимчасово заблокований'), (4, 'Заблокований')], default=0, verbose_name='Статус водія')),
                ('driver_lat', models.FloatField(blank=True, null=True, verbose_name='Широта розміщення водія')),
                ('driver_lng', models.FloatField(blank=True, null=True, verbose_name='Довгота розміщення водія')),
                ('radius_of_order_accepting', models.FloatField(default=1000.0, verbose_name='Радіус прийому заказів в кілометрах')),
            ],
            options={
                'verbose_name_plural': 'Водії',
                'verbose_name': 'водій',
            },
        ),
        migrations.CreateModel(
            name='DriverRejectedOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxi_app.Driver', verbose_name='Водій')),
            ],
            options={
                'verbose_name_plural': 'Відхилені водіями замовлення',
                'verbose_name': 'відхилені водієм замовлення',
            },
        ),
        migrations.CreateModel(
            name='DriverResponsesBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxi_app.Client', verbose_name='Клієнт')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxi_app.Driver', verbose_name='Водій')),
                ('responses', models.ManyToManyField(blank=True, to='taxi_app.ClientResponse', verbose_name='Відгуки')),
            ],
            options={
                'verbose_name_plural': 'Відгуки про водіїв',
                'verbose_name': 'відгуки про водія',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_from', models.TextField(blank=True, null=True, verbose_name='Точка відправлення')),
                ('address_to', models.TextField(blank=True, null=True, verbose_name='Точка прибуття')),
                ('distance', models.FloatField(default=0.0, verbose_name='Відстань')),
                ('is_child_seat_needed', models.BooleanField(default=False, verbose_name='Потрібне дитяче сидіння')),
                ('is_conditioner_needed', models.BooleanField(default=False, verbose_name='Потрібен кондиціонер')),
                ('order_status', models.CharField(choices=[('new', 'Нове замовлення'), ('accepted', 'Водій прийняв замовлення'), ('arrived', 'Водій прибув до клієнта'), ('executing', 'Замовлення виконується'), ('finished', 'Замовлення виконане'), ('canceled', 'Замовлення скасовано')], default='new', max_length=20)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(0, 'Готівка'), (1, 'Картка')], default=0, verbose_name='Тип оплати')),
                ('price', models.FloatField(default=0, verbose_name='Ціна замовлення')),
                ('planed_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата замовлення')),
                ('planed_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Час замовлення')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_app.Client', verbose_name='Клієнт')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxi_app.Driver', verbose_name='Водій')),
            ],
            options={
                'verbose_name_plural': 'Замовлення',
                'verbose_name': 'замовлення',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('settings_id', models.PositiveSmallIntegerField(choices=[(1, 'Ціна за кілометр'), (2, 'Мінімальна ціна замовлення'), (3, 'Ціна яка списується з водія за робочий день'), (4, 'Кількість дизлайків для штрафу'), (5, 'Дозволена кількість штрафів')], primary_key=True, serialize=False, verbose_name='Налаштування')),
                ('value', models.FloatField(default=0.0, verbose_name='Значення')),
            ],
        ),
        migrations.AddField(
            model_name='driverrejectedorders',
            name='orders',
            field=models.ManyToManyField(blank=True, to='taxi_app.Order', verbose_name='Замовлення'),
        ),
    ]
